### ISSUE TITLE
Issues with script

### ISSUE THREAD

**Issue by jhamilt0n** [venepe/install-obs-raspberry-pi#1]
The script isn't working.  Errors begin here:

~/obs-build/obs-ndi/build $ make -j4
Scanning dependencies of target obs-ndi_autogen
[  8%] Automatic MOC and UIC for target obs-ndi
[  8%] Built target obs-ndi_autogen
Scanning dependencies of target obs-ndi
[ 33%] Building CXX object CMakeFiles/obs-ndi.dir/src/obs-ndi-output.cpp.o
[ 33%] Building CXX object CMakeFiles/obs-ndi.dir/src/obs-ndi.cpp.o
[ 33%] Building CXX object CMakeFiles/obs-ndi.dir/src/obs-ndi-source.cpp.o
[ 41%] Building CXX object CMakeFiles/obs-ndi.dir/src/obs-ndi-filter.cpp.o
/home/pi/obs-build/obs-ndi/src/obs-ndi.cpp:26:10: fatal error: obs-frontend-api.h: No such file or directory
 #include <obs-frontend-api.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/obs-ndi.dir/build.make:63: CMakeFiles/obs-ndi.dir/src/obs-ndi.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/pi/obs-build/obs-ndi/src/obs-ndi-filter.cpp:24:10: fatal error: obs-frontend-api.h: No such file or directory
 #include <obs-frontend-api.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/obs-ndi.dir/build.make:102: CMakeFiles/obs-ndi.dir/src/obs-ndi-filter.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/obs-ndi.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
pi@OBSpi:~/obs-build/obs-ndi/build $ sudo make install
[  8%] Automatic MOC and UIC for target obs-ndi
[  8%] Built target obs-ndi_autogen
[ 16%] Building CXX object CMakeFiles/obs-ndi.dir/src/obs-ndi.cpp.o
/home/pi/obs-build/obs-ndi/src/obs-ndi.cpp:26:10: fatal error: obs-frontend-api.h: No such file or directory
 #include <obs-frontend-api.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/obs-ndi.dir/build.make:63: CMakeFiles/obs-ndi.dir/src/obs-ndi.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/obs-ndi.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
pi@OBSpi:~/obs-build/obs-ndi/build $ cd ../../
pi@OBSpi:~/obs-build $ echo "-----------------------------------"
-----------------------------------
pi@OBSpi:~/obs-build $ echo "        Installing OBS Websockets"
        Installing OBS Websockets
pi@OBSpi:~/obs-build $ echo "-----------------------------------"
-----------------------------------
pi@OBSpi:~/obs-build $ git clone --recursive https://github.com/venepe/obs-websocket.git
Cloning into 'obs-websocket'...
remote: Enumerating objects: 6216, done.
remote: Total 6216 (delta 0), reused 0 (delta 0), pack-reused 6216
Receiving objects: 100% (6216/6216), 1.86 MiB | 3.63 MiB/s, done.
Resolving deltas: 100% (4325/4325), done.
Submodule 'deps/asio' (https://github.com/chriskohlhoff/asio.git) registered for path 'deps/asio'
Submodule 'deps/websocketpp' (https://github.com/zaphoyd/websocketpp.git) registered for path 'deps/websocketpp'
Cloning into '/home/pi/obs-build/obs-websocket/deps/asio'...
remote: Enumerating objects: 55423, done.        
remote: Total 55423 (delta 0), reused 0 (delta 0), pack-reused 55423        
Receiving objects: 100% (55423/55423), 18.97 MiB | 7.24 MiB/s, done.
Resolving deltas: 100% (39002/39002), done.
Cloning into '/home/pi/obs-build/obs-websocket/deps/websocketpp'...
remote: Enumerating objects: 10, done.        
remote: Counting objects: 100% (10/10), done.        
remote: Compressing objects: 100% (10/10), done.        
remote: Total 12630 (delta 2), reused 1 (delta 0), pack-reused 12620        
Receiving objects: 100% (12630/12630), 8.79 MiB | 2.21 MiB/s, done.
Resolving deltas: 100% (7699/7699), done.
Submodule path 'deps/asio': checked out 'b73dc1d2c0ecb9452a87c26544d7f71e24342df6'
Submodule path 'deps/websocketpp': checked out 'c6d7e295bf5a0ab9b5f896720cc1a0e0fdc397a7'
pi@OBSpi:~/obs-build $ cd obs-websocket/
pi@OBSpi:~/obs-build/obs-websocket $ mkdir build && cd build
pi@OBSpi:~/obs-build/obs-websocket/build $ cmake -DLIBOBS_INCLUDE_DIR="/usr/share/obs/libobs/" -DCMAKE_INSTALL_PREFIX="$PREFIX" -DUSE_UBUNTU_FIX=true ..
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/obs-build/obs-websocket/build
pi@OBSpi:~/obs-build/obs-websocket/build $ make -j4
Scanning dependencies of target obs-websocket_autogen
[  3%] Automatic MOC and UIC for target obs-websocket
[  3%] Built target obs-websocket_autogen
Scanning dependencies of target obs-websocket
[  7%] Building CXX object CMakeFiles/obs-websocket.dir/src/obs-websocket.cpp.o
[ 14%] Building CXX object CMakeFiles/obs-websocket.dir/src/WSServer.cpp.o
[ 14%] Building CXX object CMakeFiles/obs-websocket.dir/src/ConnectionProperties.cpp.o
[ 17%] Building CXX object CMakeFiles/obs-websocket.dir/src/WSRequestHandler.cpp.o
In file included from /home/pi/obs-build/obs-websocket/src/WSRequestHandler.cpp:24:
/home/pi/obs-build/obs-websocket/src/Config.h:21:10: fatal error: obs-frontend-api.h: No such file or directory
 #include <obs-frontend-api.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/obs-websocket.dir/build.make:102: CMakeFiles/obs-websocket.dir/src/WSRequestHandler.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 21%] Building CXX object CMakeFiles/obs-websocket.dir/src/WSRequestHandler_General.cpp.o
/home/pi/obs-build/obs-websocket/src/obs-websocket.cpp:20:10: fatal error: obs-frontend-api.h: No such file or directory
 #include <obs-frontend-api.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/obs-websocket.dir/build.make:63: CMakeFiles/obs-websocket.dir/src/obs-websocket.cpp.o] Error 1
/home/pi/obs-build/obs-websocket/src/WSServer.cpp:27:10: fatal error: obs-frontend-api.h: No such file or directory
 #include <obs-frontend-api.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/obs-websocket.dir/build.make:76: CMakeFiles/obs-websocket.dir/src/WSServer.cpp.o] Error 1
In file included from /home/pi/obs-build/obs-websocket/src/WSRequestHandler_General.cpp:1:
/home/pi/obs-build/obs-websocket/src/WSRequestHandler.h:27:10: fatal error: obs-frontend-api.h: No such file or directory
 #include <obs-frontend-api.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/obs-websocket.dir/build.make:115: CMakeFiles/obs-websocket.dir/src/WSRequestHandler_General.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/obs-websocket.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
pi@OBSpi:~/obs-build/obs-websocket/build $ sudo make install
[  3%] Automatic MOC and UIC for target obs-websocket
[  3%] Built target obs-websocket_autogen
[  7%] Building CXX object CMakeFiles/obs-websocket.dir/src/obs-websocket.cpp.o
/home/pi/obs-build/obs-websocket/src/obs-websocket.cpp:20:10: fatal error: obs-frontend-api.h: No such file or directory
 #include <obs-frontend-api.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/obs-websocket.dir/build.make:63: CMakeFiles/obs-websocket.dir/src/obs-websocket.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/obs-websocket.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
pi@OBSpi:~/obs-build/obs-websocket/build $

Any ideas on how to resolve?

**Comment by venepe** [comment]
I recommend trying [this script to install obs](https://github.com/xbelanch/OBS4Pi/blob/main/build.sh).
